FORMAT: 1A
HOST: https://api.frost-sns.ml/

# Frost-API (日本語)

- Frost-APIはすべてのFrostクライアントがFrostのコンテンツを利用するためのAPIです。

- 権限を必要とするエンドポイントへのリクエストではヘッダーに `X-Application-Key` と `X-Access-Key` が付加されている必要があり、また、そのアプリケーションは指定された権限を持っている必要があります。

# Group Account

## account [/account]

### アカウントを作成 [POST]

#### アクセスに必要な権限
- `account_special`

+ Request (application/json)

        {
            "screen_name": "hoge",
            "password": "hogehoge",
            "name": "ほげほげ",
            "description": "ぴよぴよ"
        }

+ Response 200
    [users/id][]

# Group Applications

## applications [/applications]

+ Model (application/json)

        {
            "application": {
                "id": "abcdef123456abcdef123456",
                "created_at": 1234567890,
                "creator_id": 1,
                "name": "Test",
                "description": "テスト用のアプリケーションです。",
                "permissions": [
                    "account_read",
                    "user_read",
                    "post_read",
                    "post_write"
                ]
            }
        }

### アプリケーションの作成 [POST]

#### アクセスに必要な権限
- `application_special`

+ Request (application/json)

        {
            "name": "Test",
            "description": "テスト用のアプリケーションです。",
            "permissions": [
                "account_read",
                "user_read",
                "post_read",
                "post_write"
            ]
        }

+ Response 200
    [applications][]

## applications/id [/applications/{id}]

+ Parameters
    + id: `abcdef123456abcdef123456` (string, required) - アプリケーションID。

### アプリケーション情報を取得 [GET]

#### アクセスに必要な権限
- `application`

+ Response 200
    [applications][]

## applications/id/application_key [/applications/{id}/application_key]

+ Parameters
    + id: `abcdef123456abcdef123456` (string, required) - アプリケーションID。

+ Model (application/json)

        {
            "application_key": "abcdef123456abcdef123456-ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234.123"
        }

### アプリケーションキーの作成 [POST]

#### アクセスに必要な権限
- `application_special`

+ Response 200
    [applications/id/application_key][]

### アプリケーションキーの取得 [GET]

#### アクセスに必要な権限
- `application_special`

+ Response 200
    [applications/id/application_key][]

# Group IceAuth

## ice_auth [/ice_auth]

### IceAuthキーの作成 [POST]
#### 説明
認証を行う際に必要となります。
#### アクセスに必要な権限
- 不要

+ Request (application/json)

        {
            "application_key": "abcdef123456abcdef123456-ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234.123"
        }

+ Response 200 (application/json)

        {
            "ice_auth_key" : "abcdef123456abcdef123456-ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234.123"
        }

## ice_auth/verification_code [/ice_auth/verification_code]

### 検証コードを取得 [GET]
#### 説明
認証ホスト(Frost-Webなど)向けです。

クライアントは`ice_auth_host`権限を持つ認証ホスト上で手続きを行い、間接的に`verification_key`を得る必要があります。
#### アクセスに必要な権限
- `ice_auth_host`

+ Request (application/json)

        {
            "ice_auth_key" : "abcdef123456abcdef123456-ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234.123"
        }

+ Response 200 (application/json)

        {
            "verification_code" : "1234567890"
        }

## ice_auth/target_user [/ice_auth/target_user]

### 認証の対象ユーザーを設定 [POST]
#### 説明
認証ホスト(Frost-Webなど)向けです。

`ice_auth_host`権限を持つ認証ホストが手続きを行う際に、認証の対象となったユーザーの`user_id`をパラメータに付加してリクエストします。
#### アクセスに必要な権限
- `ice_auth_host`

+ Request (application/json)

        {
            "ice_auth_key" : "abcdef123456abcdef123456-ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234.123",
            "user_id": "abcdef123456abcdef123457"
        }

+ Response 200 (application/json)

        {
            "target_user_id" : "abcdef123456abcdef123457"
        }

## ice_auth/access_key [/ice_auth/access_key]

### アクセスキーを作成 [POST]
#### アクセスに必要な権限
- 不要

+ Request (application/json)

        {
            "ice_auth_key" : "abcdef123456abcdef123456-ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234.123",
            "verification_code" : "1234567890"
        }

+ Response 200 (application/json)

        {
            "access_key" : "abcdef123456abcdef123456-ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234.123"
        }

# Group Posts

## posts/id [/posts/{id}]

+ Parameters
    + id: `abcdef123456abcdef123456` (string, required) - ポストID。

### ポストを取得 [GET]

#### アクセスに必要な権限
- `post_read`

+ Response 200
    [posts/status][]

+ Response 200
    [posts/article][]

+ Response 200
    [posts/link_post][]

## posts/status [/posts/status]

+ Model (application/json)

        {
            "id": "abcdef123456abcdef123456",
            "created_at": 1234567891,
            "user_id": 1,
            "post_type": "status",
            "text": "hogehoge"
        }

### ステータスポストを作成 [POST]

#### アクセスに必要な権限
- `post_write`

+ Request (application/json)

        {
            "text": "hogehoge"
        }

+ Response 200
    [posts/status][]

## posts/article [/posts/article]

+ Model (application/json)

        {
            "id": "abcdef123456abcdef123457",
            "created_at": 1234567892,
            "user_id": 1,
            "post_type": "article",
            "title": "hoge",
            "description": "description text",
            "body": "hogehoge",
            "thumbnail_url": "http://hogehoge.jp/thumbnail.png"
        }

### アーティクルポストを作成 [POST]

#### アクセスに必要な権限
- `post_write`

+ Request (application/json)

        {
            "title": "hoge",
            "description": "description text",
            "body": "hogehoge",
            "thumbnail_url": "http://hogehoge.jp/thumbnail.png"
        }

+ Response 200
    [posts/article][]

## posts/link_post [/posts/link_post]

+ Model (application/json)

        {
            "id": "abcdef123456abcdef123458",
            "created_at": 1234567893,
            "user_id": 2,
            "post_type": "linkPost",
            "target_post_id": 2,
            "target_post": {
                "id": 2,
                "created_at": 1234567892,
                "user_id": 1,
                "post_type": "article",
                "title": "hoge",
                "description": "description text",
                "body": "hogehoge",
                "thumbnail_url": "http://hogehoge.jp/thumbnail.png"
            }
        }

### リンクポストを作成 [POST]

#### アクセスに必要な権限
- `post_write`

+ Request (application/json)

        {
            "target_post_id": 2
        }

+ Response 200
    [posts/link_post][]

# Group Users

## users/id [/users/{id}]

+ Parameters
    + id: `abcdef123456abcdef123456` (string, required) - ユーザーID。

+ Model (application/json)

        {
            "id": "abcdef123456abcdef123456",
            "created_at": 1234567890,
            "screen_name": "hoge",
            "name": "ほげほげ",
            "description": "ぴよぴよ"
        }

### ユーザー情報の取得 [GET]

#### アクセスに必要な権限
- `user_read`

+ Response 200
    [users/id][]

## users/id/timeline [/users/{id}/timeline]

+ Model (application/json)

        [
            {
                "id": "abcdef123456abcdef123456",
                "created_at": 1234567891,
                "user_id": 1,
                "post_type": "status",
                "text": "hogehoge"
            },
            {
                "id": "abcdef123456abcdef123457",
                "created_at": 1234567892,
                "user_id": 1,
                "post_type": "article",
                "title": "hoge",
                "description": "description text",
                "body": "hogehoge",
                "thumbnailUrl": "http://hogehoge.jp/thumbnail.png"
            },
            {
                "id": "abcdef123456abcdef123458",
                "created_at": 1234567893,
                "user_id": 2,
                "post_type": "linkPost",
                "target_post_id": 2
                "target_post": {
                    "id": 2,
                    "created_at": 1234567892,
                    "user_id": 1,
                    "post_type": "article",
                    "title": "hoge",
                    "description": "description text",
                    "body": "hogehoge",
                    "thumbnail_url": "http://hogehoge.jp/thumbnail.png"
                }
            }
        ]

### 指定ユーザーの最新の投稿一覧を取得 [GET]

#### アクセスに必要な権限
- `user_read`

+ Request (application/json)

        {
            "filter": "all",
            "limit": 3
        }

+ Response 200
    [users/id/timeline][]